import type { BedrockExplanation } from 'shared';

interface Props {
  explanation: BedrockExplanation;
}

export function ExplanationCard({ explanation }: Props) {
  return (
    <section
      className="rounded-lg p-5"
      style={{
        backgroundColor: '#EAF3FF',
        border: '1px solid #C7DCFB',
      }}
    >
      <header className="mb-3 flex items-center justify-between">
        <h3 className="text-card-title text-text-primary">
          AI explanation (Bedrock)
        </h3>
        <span
          className="rounded-pill px-3 py-1 text-small-label font-semibold uppercase tracking-wide"
          style={{ backgroundColor: '#0055D4', color: '#FFE600' }}
        >
          {explanation.confidence} confidence
        </span>
      </header>

      <div className="space-y-3 text-text-primary">
        <Block lang="EN" body={explanation.explanation_en} />
        <Block lang="BM" body={explanation.explanation_bm} />
      </div>

      <p className="mt-4 text-caption text-muted-text">
        Generated by Amazon Bedrock (Claude). Model classifies this as a{' '}
        <span className="font-semibold text-text-primary">
          {explanation.scam_type.replace('_', ' ')}
        </span>{' '}
        pattern.
      </p>
    </section>
  );
}

function Block({ lang, body }: { lang: 'EN' | 'BM'; body: string }) {
  return (
    <div className="flex gap-3">
      <span
        className="mt-[2px] inline-flex h-6 shrink-0 items-center rounded-pill px-2 text-small-label font-semibold"
        style={{ backgroundColor: '#0055D4', color: '#FFFFFF' }}
      >
        {lang}
      </span>
      <p className="text-base leading-relaxed">{body}</p>
    </div>
  );
}
